"""empty message

Revision ID: 1017636ea42c
Revises: fdee9d4d19ee
Create Date: 2025-05-17 11:25:24.284597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1017636ea42c'
down_revision = 'fdee9d4d19ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fase_atual', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usuario_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('usuario_fase_atual_constraint', 'usuario', ['usuario_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fase_atual', schema=None) as batch_op:
        batch_op.drop_constraint('usuario_fase_atual_constraint', type_='foreignkey')
        batch_op.drop_column('usuario_id')

    # ### end Alembic commands ###
