"""empty message

Revision ID: 95664124685b
Revises: a2b791e3c609
Create Date: 2025-05-17 12:38:52.279982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95664124685b'
down_revision = 'a2b791e3c609'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resposta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('correta', sa.Boolean(), nullable=False),
    sa.Column('descricao', sa.String(length=500), nullable=False),
    sa.Column('id_pergunta', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_pergunta'], ['pergunta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resposta')
    # ### end Alembic commands ###
