"""empty message

Revision ID: a2b791e3c609
Revises: 1017636ea42c
Create Date: 2025-05-17 12:32:51.464914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2b791e3c609'
down_revision = '1017636ea42c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pergunta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('posicao_no_jogo', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=500), nullable=False),
    sa.Column('dificuldade', sa.String(length=50), nullable=False),
    sa.Column('pontuacao_acerto', sa.Integer(), nullable=False),
    sa.Column('pontuacao_erro', sa.Integer(), nullable=False),
    sa.Column('id_fase', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_fase'], ['fase.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pergunta')
    # ### end Alembic commands ###
