"""'usuario'

Revision ID: b74624eda213
Revises: 7aca2efbfcb6
Create Date: 2025-05-01 15:08:03.530432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b74624eda213'
down_revision = '7aca2efbfcb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personagem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('skin', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('personagem', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_personagem_nome'), ['nome'], unique=True)
        batch_op.create_index(batch_op.f('ix_personagem_skin'), ['skin'], unique=True)

    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuario_password'), ['password'], unique=True)
        batch_op.create_index(batch_op.f('ix_usuario_username'), ['username'], unique=True)

    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_index('ix_client_email')
        batch_op.drop_index('ix_client_name')

    op.drop_table('client')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('email', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.create_index('ix_client_name', ['name'], unique=1)
        batch_op.create_index('ix_client_email', ['email'], unique=1)

    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuario_username'))
        batch_op.drop_index(batch_op.f('ix_usuario_password'))

    op.drop_table('usuario')
    with op.batch_alter_table('personagem', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_personagem_skin'))
        batch_op.drop_index(batch_op.f('ix_personagem_nome'))

    op.drop_table('personagem')
    # ### end Alembic commands ###
