"""empty message

Revision ID: d7444f7f1c44
Revises: 95664124685b
Create Date: 2025-05-17 12:54:48.361174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7444f7f1c44'
down_revision = '95664124685b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tentativa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_fase_atual', sa.Integer(), nullable=False),
    sa.Column('id_pergunta', sa.Integer(), nullable=False),
    sa.Column('id_resposta', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('horario', sa.DateTime(), nullable=True),
    sa.Column('correta', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_fase_atual'], ['fase_atual.id'], ),
    sa.ForeignKeyConstraint(['id_pergunta'], ['pergunta.id'], ),
    sa.ForeignKeyConstraint(['id_resposta'], ['resposta.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tentativa')
    # ### end Alembic commands ###
