"""empty message

Revision ID: fdee9d4d19ee
Revises: bb996c35fb2c
Create Date: 2025-05-13 19:32:08.190791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdee9d4d19ee'
down_revision = 'bb996c35fb2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('sequencia', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sequencia')
    )
    op.create_table('fase_atual',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fase_id', sa.Integer(), nullable=False),
    sa.Column('horario_inicio_fase', sa.DateTime(), nullable=True),
    sa.Column('horario_final_fase', sa.DateTime(), nullable=True),
    sa.Column('passou_fase', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['fase_id'], ['fase.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ranking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('pontos', sa.Integer(), nullable=False),
    sa.Column('tempo_total', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=1000),
               existing_nullable=True)
        batch_op.drop_index('ix_usuario_password')
        batch_op.create_index(batch_op.f('ix_usuario_password'), ['password'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuario_password'))
        batch_op.create_index('ix_usuario_password', ['password'], unique=1)
        batch_op.alter_column('password',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)

    op.drop_table('ranking')
    op.drop_table('fase_atual')
    op.drop_table('fase')
    # ### end Alembic commands ###
